# Generated by Django 4.2.7 on 2024-01-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=200)),
                ('State_population', models.BigIntegerField()),
                ('State_language', models.CharField(max_length=200)),
                ('State_capital', models.CharField(max_length=200)),
            ],
        ),
    ]
